version: "2"
services:
  php:
    container_name: phpTeste
    build: ./docker/php
    volumes:
      - .:/usr/share/nginx/html
    links:  
      - "db"
  web:
    container_name: nginxTeste
    image: "nginx:1.13.8-alpine"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - "php"
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      